# Generated by Django 3.1.14 on 2022-03-24 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0010_auto_20220224_1230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='C:\\VScode_projects\\Collect_the_pockemon\\pokemon_map\\media'),
        ),
    ]
