# Generated by Django 3.1.14 on 2022-03-27 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0016_auto_20220327_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='discription',
            field=models.TextField(blank=True, null=True),
        ),
    ]
