# Generated by Django 3.1.14 on 2022-03-28 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0019_auto_20220328_2032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemonentity',
            name='pokemon',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='pokemon_entities.pokemon', verbose_name='Эволюционировал из'),
        ),
    ]
